/**
 * scripts/gen-locales.js
 * Merges new translation keys into all locale files.
 * Run with: node scripts/gen-locales.js
 */
const fs = require("fs");
const path = require("path");

const LOCALES_DIR = path.join(__dirname, "../public/locales");
const EN = JSON.parse(fs.readFileSync(path.join(LOCALES_DIR, "en/translation.json"), "utf8"));

// ── Per-language overrides for new UI keys ────────────────────────────────────
// Keys not listed here fall back to English (i18next fallbackLng: "en")
const OVERRIDES = {
  es: {
    common: { loading: "Cargando…", error: "Error", back: "Volver", cancel: "Cancelar", continue: "Continuar", close: "Cerrar", save: "Guardar", search: "Buscar", view: "Ver", submit: "Enviar", retry: "Reintentar", reset: "Restablecer", open_menu: "Abrir menú", close_menu: "Cerrar menú", skip_to_content: "Ir al contenido principal", risk_disclosures: "Ver divulgaciones de riesgo →", page_not_found: "Página no encontrada" },
    wallet: { disconnect: "Desconectar", metamask_required: "Se requiere MetaMask o cartera compatible" },
    landing: { eyebrow: "Protocolo Facinations", heading: "Posee la Civilización.\nIntercambia Cultura.", subtitle: "Musée-Crosdale es un museo sintético de cultura en bóvedas, impulsado por el protocolo de arte fino Facinations. Elige tu rol.", role_vc: "Capitalistas de Riesgo", role_vc_desc: "Comprende el protocolo, mercado y visión detrás de Facinations.", role_collectors: "Coleccionistas y Consumidores", role_collectors_desc: "Explora bóvedas de arte fino curadas y colecciones narrativas.", role_artists: "Artistas, Dealers y Galerías", role_artists_desc: "Acuña, guarda y circula tus colecciones en Facinations.", role_partners: "Socios de Ventas", role_partners_desc: "Conoce la historia y estrategia de Facinations en el Blogazine.", btn_about: "Acerca de", btn_whitepaper: "Whitepaper", btn_gallery: "Entrar a la Galería", btn_studio: "Entrar al Studio", btn_blogazine: "Visitar Blogazine" },
    about: { eyebrow: "El Protocolo", title: "Acerca de Facinations", lead: "Facinations es una plataforma de arte fino que fractaliza obras de nivel museístico en bóvedas programables.", section_why: "Por qué ahora", section_how: "Cómo funciona", section_team: "Equipo", btn_investor: "Solicitar Dossier de Inversión" },
    vaults: { badge_live: "En vivo", badge_cached: "Caché", search_placeholder: "Buscar por nombre o ID…", loading: "Cargando bóvedas…", error: "No se pueden cargar las bóvedas ahora.", empty: "Ninguna bóveda coincide con esa búsqueda.", risk_banner: "Las tenencias de bóvedas están sujetas a riesgo de contrato inteligente, restricciones de liquidez y volatilidad.", btn_view: "Ver", btn_swap: "Intercambiar", btn_swap_restricted: "Intercambio (restringido)" },
    vaultDetail: { back: "← Volver a bóvedas", not_found: "Bóveda no encontrada.", loading_metrics: "Cargando métricas en vivo…", metrics_unavailable: "Métricas en vivo no disponibles.", section_metrics: "Métricas y Precio", section_positions: "Posiciones", label_vault_id: "ID de Bóveda", label_contract: "Contrato", label_chain: "Red", label_access: "Acceso", label_tvl: "TVL", label_share_price: "Precio por acción", label_volume_24h: "Volumen 24h", label_holders: "Tenedores", label_premium: "Premium requerido", label_open: "Acceso abierto", positions_empty: "Las posiciones aparecerán aquí cuando estén conectadas a datos en vivo.", col_asset: "Activo", col_weight: "Peso", col_value: "Valor (USD)" },
    swap: { subtitle: "Intercambia tokens a través del protocolo Facinations.", risk_banner: "Los intercambios de tokens implican riesgo de contrato inteligente, liquidez y volatilidad.", label_from: "De", label_amount: "Cantidad", label_to: "A", label_output: "Salida estimada", placeholder_amount: "ej. 1.0", fetching_quote: "Obteniendo cotización…", fee_notice: "Función premium — requiere tarifa XER", btn_quote: "Obtener Cotización", btn_quote_loading: "Obteniendo cotización…", btn_execute: "Ejecutar Intercambio (próximamente)" },
    notFound: { heading: "Página no encontrada", body: "La obra que buscas se ha movido, adquirido o nunca existió.", btn_home: "Volver al inicio", btn_gallery: "Explorar Galería" },
    kycGate: { pending_heading: "Verificación en progreso", pending_body: "Tu verificación de identidad está siendo revisada. Esto generalmente tarda menos de 5 minutos.", idle_heading: "Verificación de identidad requerida", idle_body: "Tu región requiere verificación KYC antes de acceder a {{feature}}.", btn_verify: "Verificar identidad", btn_why: "¿Por qué es necesario?" },
  },
  fr: {
    common: { loading: "Chargement…", error: "Erreur", back: "Retour", cancel: "Annuler", continue: "Continuer", close: "Fermer", save: "Enregistrer", search: "Rechercher", view: "Voir", submit: "Envoyer", retry: "Réessayer", reset: "Réinitialiser", open_menu: "Ouvrir le menu", close_menu: "Fermer le menu", skip_to_content: "Aller au contenu principal", risk_disclosures: "Voir les informations sur les risques →", page_not_found: "Page introuvable" },
    wallet: { disconnect: "Déconnecter", metamask_required: "MetaMask ou portefeuille compatible requis" },
    landing: { eyebrow: "Protocole Facinations", heading: "Possédez la Civilisation.\nÉchangez la Culture.", subtitle: "Musée-Crosdale est un musée synthétique de culture en coffres, propulsé par le protocole Facinations. Choisissez votre rôle.", role_vc: "Capital-risqueurs", role_vc_desc: "Comprenez le protocole, le marché et la vision de Facinations.", role_collectors: "Collectionneurs et Consommateurs", role_collectors_desc: "Explorez des coffres d'art curatés et des collections narratives.", role_artists: "Artistes, Marchands, Galeries", role_artists_desc: "Créez, stockez et faites circuler vos collections dans Facinations.", role_partners: "Partenaires de vente", role_partners_desc: "Découvrez l'histoire et la stratégie de Facinations dans le Blogazine.", btn_about: "À propos", btn_whitepaper: "Livre blanc", btn_gallery: "Entrer dans la Galerie", btn_studio: "Entrer dans le Studio", btn_blogazine: "Visiter le Blogazine" },
    about: { eyebrow: "Le Protocole", title: "À propos de Facinations", lead: "Facinations est une plateforme axée sur les beaux-arts qui fractionalise les œuvres muséales en coffres programmables.", section_why: "Pourquoi maintenant", section_how: "Comment ça marche", section_team: "Équipe", btn_investor: "Demander le dossier investisseur" },
    vaults: { badge_live: "En direct", badge_cached: "Cache", search_placeholder: "Rechercher par nom ou ID…", loading: "Chargement des coffres…", error: "Impossible de charger les coffres.", empty: "Aucun coffre ne correspond à cette recherche.", risk_banner: "Les avoirs en coffres sont soumis aux risques des contrats intelligents, aux contraintes de liquidité et à la volatilité.", btn_view: "Voir", btn_swap: "Échanger", btn_swap_restricted: "Échange (restreint)" },
    vaultDetail: { back: "← Retour aux coffres", not_found: "Coffre introuvable.", loading_metrics: "Chargement des métriques en direct…", metrics_unavailable: "Métriques en direct indisponibles.", section_metrics: "Métriques et Prix", section_positions: "Positions", label_vault_id: "ID du Coffre", label_contract: "Contrat", label_chain: "Réseau", label_access: "Accès", label_tvl: "TVL", label_share_price: "Prix par action", label_volume_24h: "Volume 24h", label_holders: "Détenteurs", label_premium: "Premium requis", label_open: "Accès libre", positions_empty: "Les positions apparaîtront ici une fois connectées aux données en direct.", col_asset: "Actif", col_weight: "Poids", col_value: "Valeur (USD)" },
    swap: { subtitle: "Échangez des tokens via le protocole Facinations.", risk_banner: "Les échanges de tokens impliquent des risques de contrat intelligent, de liquidité et de volatilité.", label_from: "De", label_amount: "Montant", label_to: "À", label_output: "Sortie estimée", placeholder_amount: "ex. 1.0", fetching_quote: "Récupération du devis…", fee_notice: "Fonction premium — nécessite des frais XER", btn_quote: "Obtenir un devis", btn_quote_loading: "Obtention du devis…", btn_execute: "Exécuter l'échange (bientôt)" },
    notFound: { heading: "Page introuvable", body: "L'œuvre que vous cherchez a été déplacée, acquise ou n'a jamais existé.", btn_home: "Retour à l'accueil", btn_gallery: "Parcourir la Galerie" },
    kycGate: { pending_heading: "Vérification en cours", idle_heading: "Vérification d'identité requise", btn_verify: "Vérifier l'identité", btn_why: "Pourquoi est-ce nécessaire ?" },
  },
  de: {
    common: { loading: "Wird geladen…", error: "Fehler", back: "Zurück", cancel: "Abbrechen", continue: "Weiter", close: "Schließen", save: "Speichern", search: "Suchen", view: "Ansehen", submit: "Absenden", retry: "Erneut versuchen", reset: "Zurücksetzen", open_menu: "Menü öffnen", close_menu: "Menü schließen", skip_to_content: "Zum Hauptinhalt springen", risk_disclosures: "Risikohinweise anzeigen →", page_not_found: "Seite nicht gefunden" },
    wallet: { disconnect: "Trennen", metamask_required: "MetaMask oder kompatible Wallet erforderlich" },
    landing: { eyebrow: "Facinations Protokoll", heading: "Besitze die Zivilisation.\nTausche Kultur.", subtitle: "Musée-Crosdale ist ein synthetisches Museum für Kulturschätze, betrieben vom Facinations Fine-Art-Protokoll. Wähle deine Rolle.", role_vc: "Risikokapitalgeber", role_vc_desc: "Verstehe das Protokoll, den Markt und die Vision hinter Facinations.", role_collectors: "Sammler & Konsumenten", role_collectors_desc: "Entdecke kuratierte Kunst-Tresore und Sammlungen.", role_artists: "Künstler, Händler, Galerien", role_artists_desc: "Präge, verwahre und zirkuliere deine Sammlungen in Facinations.", role_partners: "Vertriebspartner", role_partners_desc: "Erfahre die Geschichte und Strategie von Facinations im Blogazine.", btn_about: "Über uns", btn_whitepaper: "Whitepaper", btn_gallery: "Galerie betreten", btn_studio: "Studio betreten", btn_blogazine: "Blogazine besuchen" },
    about: { eyebrow: "Das Protokoll", title: "Über Facinations", lead: "Facinations ist eine Plattform für bildende Kunst, die museumswürdige Werke in programmierbare Tresore aufteilt.", section_why: "Warum jetzt", section_how: "So funktioniert es", section_team: "Team", btn_investor: "Investoren-Dossier anfordern" },
    vaults: { badge_live: "Live", badge_cached: "Cache", search_placeholder: "Nach Name oder ID suchen…", loading: "Tresore werden geladen…", error: "Tresore können gerade nicht geladen werden.", empty: "Keine Tresore entsprechen dieser Suche.", risk_banner: "Tresorbestände unterliegen Smart-Contract-Risiken, Liquiditätsbeschränkungen und Preisvolatilität.", btn_view: "Ansehen", btn_swap: "Tauschen", btn_swap_restricted: "Tausch (eingeschränkt)" },
    vaultDetail: { back: "← Zurück zu Tresoren", not_found: "Tresor nicht gefunden.", loading_metrics: "Live-Metriken werden geladen…", metrics_unavailable: "Live-Metriken nicht verfügbar.", section_metrics: "Metriken & Preis", section_positions: "Positionen", label_vault_id: "Tresor-ID", label_contract: "Vertrag", label_chain: "Netzwerk", label_access: "Zugang", label_tvl: "TVL", label_share_price: "Anteilspreis", label_volume_24h: "24h-Volumen", label_holders: "Inhaber", label_premium: "Premium erforderlich", label_open: "Offener Zugang", positions_empty: "Positionen erscheinen hier, sobald Live-Daten verbunden sind.", col_asset: "Anlage", col_weight: "Gewicht", col_value: "Wert (USD)" },
    swap: { subtitle: "Tausche Token über das Facinations-Protokoll.", risk_banner: "Token-Swaps beinhalten Smart-Contract-Risiken, Liquiditätsrisiken und Preisvolatilität.", label_from: "Von", label_amount: "Betrag", label_to: "Nach", label_output: "Geschätzte Ausgabe", placeholder_amount: "z.B. 1.0", fetching_quote: "Angebot wird abgerufen…", fee_notice: "Premium-Funktion — erfordert XER-Gebühr", btn_quote: "Angebot einholen", btn_quote_loading: "Angebot wird eingeholt…", btn_execute: "Swap ausführen (demnächst)" },
    notFound: { heading: "Seite nicht gefunden", body: "Das Werk, das Sie suchen, wurde verschoben, erworben oder hat nie existiert.", btn_home: "Zurück zur Startseite", btn_gallery: "Galerie durchsuchen" },
    kycGate: { pending_heading: "Verifizierung läuft", idle_heading: "Identitätsverifizierung erforderlich", btn_verify: "Identität verifizieren", btn_why: "Warum ist das erforderlich?" },
  },
  it: {
    common: { loading: "Caricamento…", error: "Errore", back: "Indietro", cancel: "Annulla", continue: "Continua", close: "Chiudi", save: "Salva", search: "Cerca", view: "Visualizza", submit: "Invia", retry: "Riprova", reset: "Ripristina", open_menu: "Apri menu", close_menu: "Chiudi menu", skip_to_content: "Vai al contenuto principale", risk_disclosures: "Vedi informazioni sul rischio →", page_not_found: "Pagina non trovata" },
    wallet: { disconnect: "Disconnetti", metamask_required: "MetaMask o wallet compatibile richiesto" },
    landing: { eyebrow: "Protocollo Facinations", heading: "Possiedi la Civiltà.\nScambia Cultura.", subtitle: "Musée-Crosdale è un museo sintetico di cultura in caveau, alimentato dal protocollo Facinations. Scegli il tuo ruolo.", role_vc: "Venture Capitalist", role_vc_desc: "Comprendi il protocollo, il mercato e la visione dietro Facinations.", role_collectors: "Collezionisti e Consumatori", role_collectors_desc: "Esplora caveau d'arte curati e collezioni narrative.", role_artists: "Artisti, Dealer, Gallerie", role_artists_desc: "Crea, custodisci e fai circolare le tue collezioni in Facinations.", role_partners: "Partner di Vendita", role_partners_desc: "Scopri la storia e la strategia di Facinations nel Blogazine.", btn_about: "Chi siamo", btn_whitepaper: "Whitepaper", btn_gallery: "Entra nella Galleria", btn_studio: "Entra nello Studio", btn_blogazine: "Visita il Blogazine" },
    about: { eyebrow: "Il Protocollo", title: "Informazioni su Facinations", lead: "Facinations è una piattaforma di belle arti che frazionalizza opere museali in caveau programmabili.", section_why: "Perché adesso", section_how: "Come funziona", section_team: "Team", btn_investor: "Richiedi il dossier per investitori" },
    vaults: { badge_live: "In diretta", badge_cached: "Cache", search_placeholder: "Cerca per nome o ID…", loading: "Caricamento caveau…", error: "Impossibile caricare i caveau al momento.", empty: "Nessun caveau corrisponde a quella ricerca.", risk_banner: "I portafogli dei caveau sono soggetti a rischi di smart contract, vincoli di liquidità e volatilità dei prezzi.", btn_view: "Visualizza", btn_swap: "Scambia", btn_swap_restricted: "Scambio (limitato)" },
    vaultDetail: { back: "← Torna ai caveau", not_found: "Caveau non trovato.", loading_metrics: "Caricamento metriche in diretta…", metrics_unavailable: "Metriche in diretta non disponibili.", section_metrics: "Metriche e Prezzo", section_positions: "Posizioni", label_vault_id: "ID Caveau", label_contract: "Contratto", label_chain: "Rete", label_access: "Accesso", label_tvl: "TVL", label_share_price: "Prezzo per quota", label_volume_24h: "Volume 24h", label_holders: "Detentori", label_premium: "Premium richiesto", label_open: "Accesso libero", positions_empty: "Le posizioni appariranno qui quando collegate ai dati in diretta.", col_asset: "Attività", col_weight: "Peso", col_value: "Valore (USD)" },
    swap: { subtitle: "Scambia token tramite il protocollo Facinations.", risk_banner: "Gli scambi di token comportano rischi di smart contract, liquidità e volatilità dei prezzi.", label_from: "Da", label_amount: "Importo", label_to: "A", label_output: "Output stimato", placeholder_amount: "es. 1.0", fetching_quote: "Recupero preventivo…", fee_notice: "Funzione premium — richiede commissione XER", btn_quote: "Ottieni preventivo", btn_quote_loading: "Ottenendo preventivo…", btn_execute: "Esegui Swap (prossimamente)" },
    notFound: { heading: "Pagina non trovata", body: "L'opera che stai cercando è stata spostata, acquisita o non è mai esistita.", btn_home: "Torna alla home", btn_gallery: "Sfoglia la Galleria" },
    kycGate: { pending_heading: "Verifica in corso", idle_heading: "Verifica dell'identità richiesta", btn_verify: "Verifica identità", btn_why: "Perché è richiesto?" },
  },
  "pt-BR": {
    common: { loading: "Carregando…", error: "Erro", back: "Voltar", cancel: "Cancelar", continue: "Continuar", close: "Fechar", save: "Salvar", search: "Pesquisar", view: "Ver", submit: "Enviar", retry: "Tentar novamente", reset: "Redefinir", open_menu: "Abrir menu", close_menu: "Fechar menu", skip_to_content: "Ir para o conteúdo principal", risk_disclosures: "Ver divulgações de risco →", page_not_found: "Página não encontrada" },
    wallet: { disconnect: "Desconectar", metamask_required: "MetaMask ou carteira compatível necessária" },
    landing: { eyebrow: "Protocolo Facinations", heading: "Possua a Civilização.\nTraque Cultura.", subtitle: "Musée-Crosdale é um museu sintético de cultura em cofres, impulsionado pelo protocolo de arte fina Facinations. Escolha seu papel.", role_vc: "Capitalistas de Risco", role_vc_desc: "Entenda o protocolo, mercado e visão por trás do Facinations.", role_collectors: "Colecionadores e Consumidores", role_collectors_desc: "Explore cofres de arte curados e coleções narrativas.", role_artists: "Artistas, Negociantes, Galerias", role_artists_desc: "Crie, guarde e circule suas coleções dentro do Facinations.", role_partners: "Parceiros de Vendas", role_partners_desc: "Conheça a história e estratégia do Facinations no Blogazine.", btn_about: "Sobre", btn_whitepaper: "Whitepaper", btn_gallery: "Entrar na Galeria", btn_studio: "Entrar no Estúdio", btn_blogazine: "Visitar Blogazine" },
    about: { eyebrow: "O Protocolo", title: "Sobre o Facinations", lead: "Facinations é uma plataforma voltada para arte fina que fracionaliza obras de nível museológico em cofres programáveis.", section_why: "Por que agora", section_how: "Como funciona", section_team: "Equipe", btn_investor: "Solicitar dossiê de investidor" },
    vaults: { badge_live: "Ao vivo", badge_cached: "Cache", search_placeholder: "Pesquisar por nome ou ID…", loading: "Carregando cofres…", error: "Não foi possível carregar os cofres agora.", empty: "Nenhum cofre corresponde a essa pesquisa.", risk_banner: "As posições em cofres estão sujeitas a riscos de contrato inteligente, restrições de liquidez e volatilidade.", btn_view: "Ver", btn_swap: "Trocar", btn_swap_restricted: "Troca (restrita)" },
    vaultDetail: { back: "← Voltar aos cofres", not_found: "Cofre não encontrado.", loading_metrics: "Carregando métricas ao vivo…", metrics_unavailable: "Métricas ao vivo indisponíveis.", section_metrics: "Métricas e Preço", section_positions: "Posições", label_vault_id: "ID do Cofre", label_contract: "Contrato", label_chain: "Rede", label_access: "Acesso", label_tvl: "TVL", label_share_price: "Preço por cota", label_volume_24h: "Volume 24h", label_holders: "Detentores", label_premium: "Premium necessário", label_open: "Acesso aberto", positions_empty: "As posições aparecerão aqui quando conectadas aos dados ao vivo.", col_asset: "Ativo", col_weight: "Peso", col_value: "Valor (USD)" },
    swap: { subtitle: "Troque tokens pelo protocolo Facinations.", risk_banner: "Swaps de tokens envolvem riscos de contrato inteligente, liquidez e volatilidade.", label_from: "De", label_amount: "Quantidade", label_to: "Para", label_output: "Saída estimada", placeholder_amount: "ex. 1.0", fetching_quote: "Obtendo cotação…", fee_notice: "Recurso premium — requer taxa XER", btn_quote: "Obter cotação", btn_quote_loading: "Obtendo cotação…", btn_execute: "Executar Swap (em breve)" },
    notFound: { heading: "Página não encontrada", body: "A obra que você está procurando foi movida, adquirida ou nunca existiu.", btn_home: "Voltar para o início", btn_gallery: "Explorar Galeria" },
    kycGate: { pending_heading: "Verificação em andamento", idle_heading: "Verificação de identidade necessária", btn_verify: "Verificar identidade", btn_why: "Por que isso é necessário?" },
  },
  "zh-CN": {
    common: { loading: "加载中…", error: "错误", back: "返回", cancel: "取消", continue: "继续", close: "关闭", save: "保存", search: "搜索", view: "查看", submit: "提交", retry: "重试", reset: "重置", open_menu: "打开菜单", close_menu: "关闭菜单", skip_to_content: "跳至主要内容", risk_disclosures: "查看风险披露 →", page_not_found: "页面未找到" },
    wallet: { disconnect: "断开连接", metamask_required: "需要 MetaMask 或兼容钱包" },
    landing: { eyebrow: "Facinations 协议", heading: "拥有文明。\n交换文化。", subtitle: "Musée-Crosdale 是一座由 Facinations 精艺术协议驱动的合成文化博物馆。选择你的角色。", role_vc: "风险投资人", role_vc_desc: "了解 Facinations 背后的协议、市场和愿景。", role_collectors: "收藏家和消费者", role_collectors_desc: "探索精心策划的艺术金库和叙事收藏。", role_artists: "艺术家、经纪人、画廊", role_artists_desc: "在 Facinations 中铸造、保存和传播你的藏品。", role_partners: "销售合作伙伴", role_partners_desc: "在 Blogazine 了解 Facinations 的故事和策略。", btn_about: "关于", btn_whitepaper: "白皮书", btn_gallery: "进入画廊", btn_studio: "进入工作室", btn_blogazine: "访问 Blogazine" },
    about: { eyebrow: "协议", title: "关于 Facinations", lead: "Facinations 是一个以精艺术为核心的平台，将博物馆级作品分解为可编程金库。", section_why: "为什么是现在", section_how: "如何运作", section_team: "团队", btn_investor: "申请投资者资料" },
    vaults: { badge_live: "实时", badge_cached: "缓存", search_placeholder: "按名称或 ID 搜索…", loading: "加载金库中…", error: "暂时无法加载金库。", empty: "没有金库匹配该搜索。", risk_banner: "金库持仓受智能合约风险、流动性限制和价格波动影响。", btn_view: "查看", btn_swap: "兑换", btn_swap_restricted: "兑换（受限）" },
    vaultDetail: { back: "← 返回金库", not_found: "未找到金库。", loading_metrics: "加载实时指标中…", metrics_unavailable: "实时指标不可用。", section_metrics: "指标与价格", section_positions: "头寸", label_vault_id: "金库 ID", label_contract: "合约", label_chain: "链", label_access: "访问", label_tvl: "TVL", label_share_price: "份额价格", label_volume_24h: "24h 成交量", label_holders: "持有者", label_premium: "需要高级权限", label_open: "开放访问", positions_empty: "连接实时数据后，头寸将显示在此处。", col_asset: "资产", col_weight: "权重", col_value: "价值（USD）" },
    swap: { subtitle: "通过 Facinations 协议交换代币。", risk_banner: "代币兑换涉及智能合约风险、流动性风险和价格波动。", label_from: "从", label_amount: "数量", label_to: "至", label_output: "预计输出", placeholder_amount: "例如 1.0", fetching_quote: "正在获取报价…", fee_notice: "高级功能 — 需要 XER 费用", btn_quote: "获取报价", btn_quote_loading: "获取报价中…", btn_execute: "执行兑换（即将推出）" },
    notFound: { heading: "页面未找到", body: "您寻找的作品已移动、已被收购或从未存在过。", btn_home: "返回首页", btn_gallery: "浏览画廊" },
    kycGate: { pending_heading: "验证进行中", idle_heading: "需要身份验证", btn_verify: "验证身份", btn_why: "为什么需要这个？" },
  },
  ko: {
    common: { loading: "로딩 중…", error: "오류", back: "뒤로", cancel: "취소", continue: "계속", close: "닫기", save: "저장", search: "검색", view: "보기", submit: "제출", retry: "다시 시도", reset: "초기화", open_menu: "메뉴 열기", close_menu: "메뉴 닫기", skip_to_content: "메인 콘텐츠로 건너뛰기", risk_disclosures: "위험 공시 보기 →", page_not_found: "페이지를 찾을 수 없음" },
    wallet: { disconnect: "연결 해제", metamask_required: "MetaMask 또는 호환 가능한 지갑 필요" },
    landing: { eyebrow: "Facinations 프로토콜", heading: "문명을 소유하세요.\n문화를 교환하세요.", subtitle: "Musée-Crosdale은 Facinations 순수 예술 프로토콜이 운영하는 합성 문화 박물관입니다. 역할을 선택하세요.", role_vc: "벤처 캐피털리스트", role_vc_desc: "Facinations 뒤에 있는 프로토콜, 시장 및 비전을 이해하세요.", role_collectors: "수집가 및 소비자", role_collectors_desc: "큐레이션된 파인 아트 볼트와 내러티브 컬렉션을 탐색하세요.", role_artists: "예술가, 딜러, 갤러리", role_artists_desc: "Facinations에서 컬렉션을 주조, 보관 및 유통하세요.", role_partners: "영업 파트너", role_partners_desc: "Blogazine에서 Facinations의 이야기와 전략을 알아보세요.", btn_about: "소개", btn_whitepaper: "백서", btn_gallery: "갤러리 입장", btn_studio: "스튜디오 입장", btn_blogazine: "Blogazine 방문" },
    about: { eyebrow: "프로토콜", title: "Facinations 소개", lead: "Facinations는 박물관급 작품을 프로그래밍 가능한 볼트로 분할하는 순수 예술 우선 플랫폼입니다.", section_why: "왜 지금인가", section_how: "작동 방식", section_team: "팀", btn_investor: "투자자 자료 요청" },
    vaults: { badge_live: "실시간", badge_cached: "캐시", search_placeholder: "이름 또는 ID로 검색…", loading: "볼트 로딩 중…", error: "현재 볼트를 불러올 수 없습니다.", empty: "검색에 일치하는 볼트가 없습니다.", risk_banner: "볼트 보유는 스마트 컨트랙트 위험, 유동성 제약 및 가격 변동성을 수반합니다.", btn_view: "보기", btn_swap: "스왑", btn_swap_restricted: "스왑 (제한됨)" },
    vaultDetail: { back: "← 볼트로 돌아가기", not_found: "볼트를 찾을 수 없습니다.", loading_metrics: "실시간 지표 로딩 중…", metrics_unavailable: "실시간 지표를 사용할 수 없습니다.", section_metrics: "지표 및 가격", section_positions: "포지션", label_vault_id: "볼트 ID", label_contract: "컨트랙트", label_chain: "체인", label_access: "접근", label_tvl: "TVL", label_share_price: "주식 가격", label_volume_24h: "24시간 거래량", label_holders: "보유자", label_premium: "프리미엄 필요", label_open: "개방 접근", positions_empty: "실시간 데이터에 연결되면 포지션이 여기에 표시됩니다.", col_asset: "자산", col_weight: "비중", col_value: "가치 (USD)" },
    swap: { subtitle: "Facinations 프로토콜을 통해 토큰을 교환하세요.", risk_banner: "토큰 스왑은 스마트 컨트랙트 위험, 유동성 위험 및 가격 변동성을 수반합니다.", label_from: "보내기", label_amount: "수량", label_to: "받기", label_output: "예상 출력", placeholder_amount: "예: 1.0", fetching_quote: "견적 가져오는 중…", fee_notice: "프리미엄 기능 — XER 수수료 필요", btn_quote: "견적 가져오기", btn_quote_loading: "견적 가져오는 중…", btn_execute: "스왑 실행 (출시 예정)" },
    notFound: { heading: "페이지를 찾을 수 없음", body: "찾고 있는 작품은 이동되었거나, 취득되었거나, 존재하지 않습니다.", btn_home: "홈으로 돌아가기", btn_gallery: "갤러리 둘러보기" },
    kycGate: { pending_heading: "인증 진행 중", idle_heading: "신원 인증 필요", btn_verify: "신원 인증", btn_why: "왜 필요한가요?" },
  },
  ja: {
    common: { loading: "読み込み中…", error: "エラー", back: "戻る", cancel: "キャンセル", continue: "続ける", close: "閉じる", save: "保存", search: "検索", view: "表示", submit: "送信", retry: "再試行", reset: "リセット", open_menu: "メニューを開く", close_menu: "メニューを閉じる", skip_to_content: "メインコンテンツへ", risk_disclosures: "リスク開示を見る →", page_not_found: "ページが見つかりません" },
    wallet: { disconnect: "切断", metamask_required: "MetaMaskまたは互換性のあるウォレットが必要です" },
    landing: { eyebrow: "Facionationsプロトコル", heading: "文明を所有する。\n文化を交換する。", subtitle: "Musée-Crosdaleは、Facionationsファインアートプロトコルによって運営される合成文化博物館です。役割を選択してください。", role_vc: "ベンチャーキャピタリスト", role_vc_desc: "Facionationsの背後にあるプロトコル、市場、ビジョンを理解する。", role_collectors: "コレクターと消費者", role_collectors_desc: "キュレーションされたファインアートヴォールトとナラティブコレクションを探索する。", role_artists: "アーティスト、ディーラー、ギャラリー", role_artists_desc: "Facionationsでコレクションをミント、保管、流通させる。", role_partners: "販売パートナー", role_partners_desc: "BlogazineでFacionationsのストーリーと戦略を学ぶ。", btn_about: "概要", btn_whitepaper: "ホワイトペーパー", btn_gallery: "ギャラリーへ", btn_studio: "スタジオへ", btn_blogazine: "Blogazineを訪問" },
    about: { eyebrow: "プロトコル", title: "Facionationsについて", lead: "Facionationsはミュージアム級の作品をプログラム可能なヴォールトに分割するファインアート優先プラットフォームです。", section_why: "なぜ今なのか", section_how: "仕組み", section_team: "チーム", btn_investor: "投資家資料を請求" },
    vaults: { badge_live: "ライブ", badge_cached: "キャッシュ", search_placeholder: "名前またはIDで検索…", loading: "ヴォールトを読み込み中…", error: "現在ヴォールトを読み込めません。", empty: "その検索に一致するヴォールトはありません。", risk_banner: "ヴォールト保有はスマートコントラクトリスク、流動性制約、価格変動の対象となります。", btn_view: "表示", btn_swap: "スワップ", btn_swap_restricted: "スワップ（制限あり）" },
    vaultDetail: { back: "← ヴォールトに戻る", not_found: "ヴォールトが見つかりません。", loading_metrics: "ライブメトリクスを読み込み中…", metrics_unavailable: "ライブメトリクスを利用できません。", section_metrics: "メトリクスと価格", section_positions: "ポジション", label_vault_id: "ヴォールトID", label_contract: "コントラクト", label_chain: "チェーン", label_access: "アクセス", label_tvl: "TVL", label_share_price: "シェア価格", label_volume_24h: "24時間取引量", label_holders: "保有者", label_premium: "プレミアム必須", label_open: "オープンアクセス", positions_empty: "ライブデータに接続されると、ポジションがここに表示されます。", col_asset: "資産", col_weight: "ウェイト", col_value: "価値（USD）" },
    swap: { subtitle: "Facionationsプロトコルを通じてトークンを交換します。", risk_banner: "トークンスワップにはスマートコントラクトリスク、流動性リスク、価格変動が伴います。", label_from: "送信元", label_amount: "金額", label_to: "送信先", label_output: "推定出力", placeholder_amount: "例: 1.0", fetching_quote: "見積もりを取得中…", fee_notice: "プレミアム機能 — XER手数料が必要", btn_quote: "見積もりを取得", btn_quote_loading: "見積もりを取得中…", btn_execute: "スワップを実行（近日公開）" },
    notFound: { heading: "ページが見つかりません", body: "お探しの作品は移動、取得、または存在しなかった可能性があります。", btn_home: "ホームに戻る", btn_gallery: "ギャラリーを閲覧" },
    kycGate: { pending_heading: "確認処理中", idle_heading: "本人確認が必要", btn_verify: "本人確認", btn_why: "なぜ必要ですか？" },
  },
  ru: {
    common: { loading: "Загрузка…", error: "Ошибка", back: "Назад", cancel: "Отмена", continue: "Продолжить", close: "Закрыть", save: "Сохранить", search: "Поиск", view: "Просмотр", submit: "Отправить", retry: "Повторить", reset: "Сбросить", open_menu: "Открыть меню", close_menu: "Закрыть меню", skip_to_content: "Перейти к основному содержимому", risk_disclosures: "Смотреть раскрытие рисков →", page_not_found: "Страница не найдена" },
    wallet: { disconnect: "Отключить", metamask_required: "Требуется MetaMask или совместимый кошелёк" },
    landing: { eyebrow: "Протокол Facinations", heading: "Владей цивилизацией.\nОбменяй культуру.", subtitle: "Musée-Crosdale — синтетический музей хранилищ культуры, работающий на протоколе изящных искусств Facinations. Выберите свою роль.", role_vc: "Венчурные капиталисты", role_vc_desc: "Познакомьтесь с протоколом, рынком и видением Facinations.", role_collectors: "Коллекционеры и потребители", role_collectors_desc: "Исследуйте кураторские хранилища изящного искусства и нарративные коллекции.", role_artists: "Художники, дилеры, галереи", role_artists_desc: "Создавайте, храните и распространяйте свои коллекции в Facinations.", role_partners: "Торговые партнёры", role_partners_desc: "Узнайте историю и стратегию Facinations в Blogazine.", btn_about: "О нас", btn_whitepaper: "Белая книга", btn_gallery: "Войти в галерею", btn_studio: "Войти в студию", btn_blogazine: "Посетить Blogazine" },
    about: { eyebrow: "Протокол", title: "О Facinations", lead: "Facinations — платформа, ориентированная на изящное искусство, которая дробит музейные работы на программируемые хранилища.", section_why: "Почему сейчас", section_how: "Как это работает", section_team: "Команда", btn_investor: "Запросить инвестиционный досье" },
    vaults: { badge_live: "Онлайн", badge_cached: "Кэш", search_placeholder: "Поиск по имени или ID…", loading: "Загрузка хранилищ…", error: "Не удаётся загрузить хранилища.", empty: "Нет хранилищ, соответствующих поиску.", risk_banner: "Позиции в хранилищах подвержены рискам смарт-контрактов, ограничениям ликвидности и волатильности цен.", btn_view: "Просмотр", btn_swap: "Обменять", btn_swap_restricted: "Обмен (ограничен)" },
    vaultDetail: { back: "← Вернуться к хранилищам", not_found: "Хранилище не найдено.", loading_metrics: "Загрузка показателей в реальном времени…", metrics_unavailable: "Показатели в реальном времени недоступны.", section_metrics: "Показатели и цена", section_positions: "Позиции", label_vault_id: "ID хранилища", label_contract: "Контракт", label_chain: "Сеть", label_access: "Доступ", label_tvl: "TVL", label_share_price: "Цена доли", label_volume_24h: "Объём за 24ч", label_holders: "Владельцы", label_premium: "Требуется Premium", label_open: "Открытый доступ", positions_empty: "Позиции появятся здесь после подключения к реальным данным.", col_asset: "Актив", col_weight: "Вес", col_value: "Стоимость (USD)" },
    swap: { subtitle: "Обменивайте токены через протокол Facinations.", risk_banner: "Обмен токенов сопряжён с рисками смарт-контрактов, ликвидности и волатильностью цен.", label_from: "Из", label_amount: "Сумма", label_to: "В", label_output: "Ожидаемый результат", placeholder_amount: "напр. 1.0", fetching_quote: "Получение котировки…", fee_notice: "Премиум-функция — требуется комиссия XER", btn_quote: "Получить котировку", btn_quote_loading: "Получение котировки…", btn_execute: "Выполнить обмен (скоро)" },
    notFound: { heading: "Страница не найдена", body: "Произведение, которое вы ищете, было перемещено, приобретено или никогда не существовало.", btn_home: "Вернуться на главную", btn_gallery: "Просмотреть галерею" },
    kycGate: { pending_heading: "Верификация в процессе", idle_heading: "Требуется верификация личности", btn_verify: "Верифицировать личность", btn_why: "Почему это необходимо?" },
  },
  ar: {
    common: { loading: "جار التحميل…", error: "خطأ", back: "رجوع", cancel: "إلغاء", continue: "متابعة", close: "إغلاق", save: "حفظ", search: "بحث", view: "عرض", submit: "إرسال", retry: "إعادة المحاولة", reset: "إعادة تعيين", open_menu: "فتح القائمة", close_menu: "إغلاق القائمة", skip_to_content: "تخطى إلى المحتوى الرئيسي", risk_disclosures: "انظر إفصاحات المخاطر ←", page_not_found: "الصفحة غير موجودة" },
    wallet: { disconnect: "قطع الاتصال", metamask_required: "يلزم وجود MetaMask أو محفظة متوافقة" },
    landing: { eyebrow: "بروتوكول Facinations", heading: "امتلك الحضارة.\nتبادل الثقافة.", subtitle: "Musée-Crosdale متحف اصطناعي للثقافة المخزنة، يعمل بموجب بروتوكول الفنون الجميلة Facinations. اختر دورك.", role_vc: "رأس المال الجريء", role_vc_desc: "افهم البروتوكول والسوق والرؤية وراء Facinations.", role_collectors: "الجامعون والمستهلكون", role_collectors_desc: "استكشف خزائن الفنون الجميلة المنسقة والمجموعات السردية.", role_artists: "الفنانون والتجار والغاليريهات", role_artists_desc: "أنشئ واحفظ وروّج لمجموعاتك داخل Facinations.", role_partners: "شركاء المبيعات", role_partners_desc: "تعرف على قصة واستراتيجية Facinations في Blogazine.", btn_about: "حول", btn_whitepaper: "الورقة البيضاء", btn_gallery: "الدخول إلى المعرض", btn_studio: "الدخول إلى الاستوديو", btn_blogazine: "زيارة Blogazine" },
    about: { eyebrow: "البروتوكول", title: "حول Facinations", lead: "Facinations منصة تركز على الفنون الجميلة وتجزئ الأعمال ذات المستوى المتحفي إلى خزائن قابلة للبرمجة.", section_why: "لماذا الآن", section_how: "كيف يعمل", section_team: "الفريق", btn_investor: "طلب ملف المستثمر" },
    vaults: { badge_live: "مباشر", badge_cached: "ذاكرة تخزين مؤقت", search_placeholder: "ابحث بالاسم أو المعرّف…", loading: "تحميل الخزائن…", error: "تعذّر تحميل الخزائن الآن.", empty: "لا توجد خزائن تطابق هذا البحث.", risk_banner: "تخضع ممتلكات الخزائن لمخاطر العقود الذكية وقيود السيولة وتقلبات الأسعار.", btn_view: "عرض", btn_swap: "تبادل", btn_swap_restricted: "تبادل (مقيّد)" },
    vaultDetail: { back: "← العودة إلى الخزائن", not_found: "الخزنة غير موجودة.", loading_metrics: "تحميل المقاييس المباشرة…", metrics_unavailable: "المقاييس المباشرة غير متاحة.", section_metrics: "المقاييس والسعر", section_positions: "المراكز", label_vault_id: "معرّف الخزنة", label_contract: "العقد", label_chain: "الشبكة", label_access: "الوصول", label_tvl: "TVL", label_share_price: "سعر الحصة", label_volume_24h: "حجم 24 ساعة", label_holders: "الحاملون", label_premium: "يلزم الاشتراك المميّز", label_open: "وصول مفتوح", positions_empty: "ستظهر المراكز هنا عند ربطها بالبيانات المباشرة.", col_asset: "الأصل", col_weight: "الوزن", col_value: "القيمة (USD)" },
    swap: { subtitle: "تبادل الرموز عبر بروتوكول Facinations.", risk_banner: "تنطوي مبادلات الرموز على مخاطر العقود الذكية والسيولة وتقلب الأسعار.", label_from: "من", label_amount: "المبلغ", label_to: "إلى", label_output: "الناتج المقدّر", placeholder_amount: "مثال: 1.0", fetching_quote: "جار جلب الاقتباس…", fee_notice: "ميزة مميّزة — تتطلب رسوم XER", btn_quote: "الحصول على اقتباس", btn_quote_loading: "جار الحصول على اقتباس…", btn_execute: "تنفيذ التبادل (قريباً)" },
    notFound: { heading: "الصفحة غير موجودة", body: "العمل الذي تبحث عنه تم نقله أو اقتناؤه أو لم يكن موجوداً قط.", btn_home: "العودة إلى الرئيسية", btn_gallery: "تصفح المعرض" },
    kycGate: { pending_heading: "التحقق جارٍ", idle_heading: "التحقق من الهوية مطلوب", btn_verify: "التحقق من الهوية", btn_why: "لماذا هذا مطلوب؟" },
  },
  hi: {
    common: { loading: "लोड हो रहा है…", error: "त्रुटि", back: "वापस", cancel: "रद्द करें", continue: "जारी रखें", close: "बंद करें", save: "सहेजें", search: "खोजें", view: "देखें", submit: "सबमिट करें", retry: "पुनः प्रयास करें", reset: "रीसेट करें", open_menu: "मेनू खोलें", close_menu: "मेनू बंद करें", skip_to_content: "मुख्य सामग्री पर जाएं", risk_disclosures: "जोखिम प्रकटीकरण देखें →", page_not_found: "पृष्ठ नहीं मिला" },
    wallet: { disconnect: "डिस्कनेक्ट", metamask_required: "MetaMask या संगत वॉलेट आवश्यक है" },
    landing: { eyebrow: "Facinations प्रोटोकॉल", heading: "सभ्यता के मालिक बनें।\nसंस्कृति का आदान-प्रदान करें।", subtitle: "Musée-Crosdale Facinations ललित कला प्रोटोकॉल द्वारा संचालित वॉल्टेड संस्कृति का एक सिंथेटिक संग्रहालय है। अपनी भूमिका चुनें।", role_vc: "वेंचर कैपिटलिस्ट", role_vc_desc: "Facinations के पीछे के प्रोटोकॉल, बाजार और दृष्टिकोण को समझें।", role_collectors: "संग्राहक और उपभोक्ता", role_collectors_desc: "क्यूरेटेड ललित कला वॉल्ट और कथा संग्रह का अन्वेषण करें।", role_artists: "कलाकार, डीलर, गैलरी", role_artists_desc: "Facinations में अपने संग्रह को मिंट, वॉल्ट और प्रचलित करें।", role_partners: "बिक्री भागीदार", role_partners_desc: "Blogazine में Facinations की कहानी और रणनीति जानें।", btn_about: "के बारे में", btn_whitepaper: "श्वेत पत्र", btn_gallery: "गैलरी में प्रवेश करें", btn_studio: "स्टूडियो में प्रवेश करें", btn_blogazine: "Blogazine देखें" },
    about: { eyebrow: "प्रोटोकॉल", title: "Facinations के बारे में", lead: "Facinations एक ललित कला-प्रथम प्लेटफ़ॉर्म है जो संग्रहालय-ग्रेड कार्यों को प्रोग्रामयोग्य वॉल्ट में विभाजित करता है।", section_why: "अभी क्यों", section_how: "यह कैसे काम करता है", section_team: "टीम", btn_investor: "निवेशक डोसियर का अनुरोध करें" },
    vaults: { badge_live: "लाइव", badge_cached: "कैश्ड", search_placeholder: "नाम या ID से खोजें…", loading: "वॉल्ट लोड हो रहे हैं…", error: "अभी वॉल्ट लोड नहीं हो सकते।", empty: "उस खोज से मेल खाने वाला कोई वॉल्ट नहीं।", risk_banner: "वॉल्ट होल्डिंग स्मार्ट कॉन्ट्रैक्ट जोखिम, तरलता बाधाओं और मूल्य अस्थिरता के अधीन हैं।", btn_view: "देखें", btn_swap: "स्वैप", btn_swap_restricted: "स्वैप (प्रतिबंधित)" },
    vaultDetail: { back: "← वॉल्ट पर वापस जाएं", not_found: "वॉल्ट नहीं मिला।", loading_metrics: "लाइव मेट्रिक्स लोड हो रहे हैं…", metrics_unavailable: "लाइव मेट्रिक्स अनुपलब्ध।", section_metrics: "मेट्रिक्स और मूल्य", section_positions: "पोजिशन", label_vault_id: "वॉल्ट ID", label_contract: "कॉन्ट्रैक्ट", label_chain: "चेन", label_access: "पहुंच", label_tvl: "TVL", label_share_price: "शेयर मूल्य", label_volume_24h: "24h वॉल्यूम", label_holders: "धारक", label_premium: "प्रीमियम आवश्यक", label_open: "खुली पहुंच", positions_empty: "लाइव डेटा से जुड़ने पर यहां पोजिशन दिखाई देंगी।", col_asset: "एसेट", col_weight: "भार", col_value: "मूल्य (USD)" },
    swap: { subtitle: "Facinations प्रोटोकॉल के माध्यम से टोकन का आदान-प्रदान करें।", risk_banner: "टोकन स्वैप में स्मार्ट कॉन्ट्रैक्ट जोखिम, तरलता जोखिम और मूल्य अस्थिरता शामिल है।", label_from: "से", label_amount: "राशि", label_to: "को", label_output: "अनुमानित आउटपुट", placeholder_amount: "जैसे 1.0", fetching_quote: "कोटेशन प्राप्त हो रहा है…", fee_notice: "प्रीमियम सुविधा — XER शुल्क आवश्यक है", btn_quote: "कोटेशन प्राप्त करें", btn_quote_loading: "कोटेशन प्राप्त हो रहा है…", btn_execute: "स्वैप निष्पादित करें (जल्द आ रहा है)" },
    notFound: { heading: "पृष्ठ नहीं मिला", body: "जो कार्य आप ढूंढ रहे हैं वह स्थानांतरित हो गया, अधिग्रहीत हो गया, या कभी अस्तित्व में नहीं था।", btn_home: "होम पर वापस जाएं", btn_gallery: "गैलरी ब्राउज़ करें" },
    kycGate: { pending_heading: "सत्यापन प्रगति में है", idle_heading: "पहचान सत्यापन आवश्यक है", btn_verify: "पहचान सत्यापित करें", btn_why: "यह क्यों आवश्यक है?" },
  },
};

// Deep merge: override values into base, recursively
function deepMerge(base, override) {
  const result = { ...base };
  for (const [k, v] of Object.entries(override)) {
    if (v && typeof v === "object" && !Array.isArray(v) && base[k] && typeof base[k] === "object") {
      result[k] = deepMerge(base[k], v);
    } else {
      result[k] = v;
    }
  }
  return result;
}

const langs = ["es", "fr", "de", "it", "pt-BR", "zh-CN", "ko", "ja", "ru", "ar", "hi"];

for (const lang of langs) {
  const file = path.join(LOCALES_DIR, lang, "translation.json");
  const existing = fs.existsSync(file)
    ? JSON.parse(fs.readFileSync(file, "utf8"))
    : {};

  // Start from EN as base (catches any missing keys → i18next fallback)
  // then layer existing translations, then our new overrides
  const merged = deepMerge(deepMerge(EN, existing), OVERRIDES[lang] || {});

  fs.writeFileSync(file, JSON.stringify(merged, null, 2));
  console.log(`✓ ${lang}`);
}
console.log("Done.");
